osx_image: xcode7.3
language: objective-c
xcode_project: v2ex-iOS.xcodeproj # path to your xcodeproj folder
xcode_scheme: v2ex-dev
script: xctool -project v2ex-iOS.xcodeproj -scheme v2ex-dev build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

cache: cocoapods

before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install
